from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .contracts import IntegrityCheck, IntegrityReport

TARGETS: dict[str, dict[str, Any]] = {
    "stage140": {
        "label": "Stage140",
        "version": "1.40.0",
        "title": "Release Integrity & Product Proof Gate",
        "required_files": [
            "docs/stages/stage140.md",
            "docs/proposals/stage140_release_integrity_product_proof_proposal.md",
            "docs/architecture/stage140_release_integrity_product_proof_blueprint.md",
            "docs/development/stage140_developer_handoff.md",
            "manifests/stage140_manifest.json",
            "manifests/stage140_release_integrity_manifest.json",
            "manifests/stage140_branchpoint_trace_manifest.json",
            "manifests/live_core_stage140_overlay.json",
            "release/current/stage140_release_asset_manifest.json",
            "samples/korean_drama_family_secret/project.json",
            "benchmarks/longform_output/expected_metrics.json",
        ],
    },
    "stage141": {
        "label": "Stage141",
        "version": "1.41.0",
        "title": "Prose Generation E2E Harness",
        "required_files": [
            "docs/stages/stage141.md",
            "docs/proposals/stage141_proposal.md",
            "docs/architecture/stage141_blueprint.md",
            "docs/development/stage141_developer_handoff.md",
            "manifests/stage141_manifest.json",
            "manifests/stage141_prose_generation_e2e_manifest.json",
            "manifests/stage141_branchpoint_trace_manifest.json",
            "manifests/live_core_stage141_overlay.json",
            "release/current/stage141_release_asset_manifest.json",
            "release/current/stage141_prose_generation_e2e_report.json",
            "benchmarks/longform_output/results/stage141_scene_001_benchmark_result.json",
            "benchmarks/longform_output/results/stage141_scene_001_rendered.md",
        ],
    },
    "stage142": {
        "label": "Stage142",
        "version": "1.42.0",
        "title": "Longform Benchmark Pack",
        "required_files": [
            "docs/stages/stage142.md",
            "docs/proposals/stage142_proposal.md",
            "docs/architecture/stage142_blueprint.md",
            "docs/development/stage142_developer_handoff.md",
            "manifests/stage142_manifest.json",
            "manifests/stage142_longform_benchmark_pack_manifest.json",
            "manifests/stage142_branchpoint_trace_manifest.json",
            "manifests/live_core_stage142_overlay.json",
            "release/current/stage142_release_asset_manifest.json",
            "release/current/stage142_longform_benchmark_pack_report.json",
            "benchmarks/longform_output/results/stage142_benchmark_pack_summary.json",
            "benchmarks/longform_output/results/stage142_rendered_samples.json",
        ],
    },
    "stage143": {
        "label": "Stage143",
        "version": "1.43.0",
        "title": "User CLI/API Minimum Docs",
        "required_files": [
            "docs/stages/stage143.md",
            "docs/proposals/stage143_proposal.md",
            "docs/architecture/stage143_blueprint.md",
            "docs/development/stage143_developer_handoff.md",
            "docs/user/cli_quickstart.md",
            "docs/user/api_minimum.md",
            "docs/user/examples/render_request.json",
            "docs/user/examples/render_response.json",
            "manifests/stage143_manifest.json",
            "manifests/stage143_user_cli_api_docs_manifest.json",
            "manifests/stage143_branchpoint_trace_manifest.json",
            "manifests/live_core_stage143_overlay.json",
            "release/current/stage143_release_asset_manifest.json",
            "release/current/stage143_user_cli_api_docs_report.json",
            "release/current/stage143_user_cli_api_docs_pack/cli_contract.json",
            "release/current/stage143_user_cli_api_docs_pack/api_contract.json",
            "release/current/stage143_user_cli_api_docs_pack/user_docs_index.json",
        ],
    },
    "stage144": {
        "label": "Stage144",
        "version": "1.44.0",
        "title": "Split CI Runtime Strategy",
        "required_files": [
            "docs/stages/stage144.md",
            "docs/proposals/stage144_proposal.md",
            "docs/architecture/stage144_blueprint.md",
            "docs/development/stage144_developer_handoff.md",
            "manifests/stage144_manifest.json",
            "manifests/stage144_split_ci_runtime_strategy_manifest.json",
            "manifests/stage144_branchpoint_trace_manifest.json",
            "manifests/live_core_stage144_overlay.json",
            "release/current/stage144_release_asset_manifest.json",
            "release/current/stage144_split_ci_runtime_strategy_report.json",
            "release/current/stage144_split_ci_runtime_strategy_pack/workflow_inventory.json",
            "release/current/stage144_split_ci_runtime_strategy_pack/runtime_lane_matrix.json",
            "release/current/stage144_split_ci_runtime_strategy_pack/workflow_trigger_summary.json",
            "release/current/stage144_split_ci_runtime_strategy_pack/release_surface_contract.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage145": {
        "label": "Stage145",
        "version": "1.45.0",
        "title": "Body Constitution",
        "required_files": [
            "docs/stages/stage145.md",
            "docs/proposals/stage145_body_constitution_proposal.md",
            "docs/architecture/stage145_body_constitution_blueprint.md",
            "docs/development/stage145_developer_handoff.md",
            "manifests/stage145_manifest.json",
            "manifests/stage145_body_constitution_manifest.json",
            "manifests/stage145_branchpoint_trace_manifest.json",
            "manifests/live_core_stage145_overlay.json",
            "release/current/stage145_release_asset_manifest.json",
            "release/current/stage145_body_constitution_report.json",
            "release/current/stage145_body_constitution_pack/formula_classification.json",
            "release/current/stage145_body_constitution_pack/constitution_invariants.json",
            "release/current/stage145_body_constitution_pack/body_layer_map.json",
            "release/current/stage145_body_constitution_pack/stage150_entry_criteria.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage146": {
        "label": "Stage146",
        "version": "1.46.0",
        "title": "Narrative State Contract",
        "required_files": [
            "docs/stages/stage146.md",
            "docs/proposals/stage146_narrative_state_contract_proposal.md",
            "docs/architecture/stage146_narrative_state_contract_blueprint.md",
            "docs/development/stage146_developer_handoff.md",
            "manifests/stage146_manifest.json",
            "manifests/stage146_narrative_state_contract_manifest.json",
            "manifests/stage146_branchpoint_trace_manifest.json",
            "manifests/live_core_stage146_overlay.json",
            "release/current/stage146_release_asset_manifest.json",
            "release/current/stage146_narrative_state_contract_report.json",
            "release/current/stage146_narrative_state_contract_pack/state_shape_catalog.json",
            "release/current/stage146_narrative_state_contract_pack/state_hierarchy.json",
            "release/current/stage146_narrative_state_contract_pack/continuity_rulebook.json",
            "release/current/stage146_narrative_state_contract_pack/reveal_boundary_matrix.json",
            "release/current/stage146_narrative_state_contract_pack/stage147_entry_signals.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage147": {
        "label": "Stage147",
        "version": "1.47.0",
        "title": "Project Manifest Body",
        "required_files": [
            "docs/stages/stage147.md",
            "docs/proposals/stage147_project_manifest_body_proposal.md",
            "docs/architecture/stage147_project_manifest_body_blueprint.md",
            "docs/development/stage147_developer_handoff.md",
            "manifests/stage147_manifest.json",
            "manifests/stage147_project_manifest_body_manifest.json",
            "manifests/stage147_branchpoint_trace_manifest.json",
            "manifests/live_core_stage147_overlay.json",
            "release/current/stage147_release_asset_manifest.json",
            "release/current/stage147_project_manifest_body_report.json",
            "release/current/stage147_project_manifest_body_pack/canonical_manifest_bundle.json",
            "release/current/stage147_project_manifest_body_pack/project_manifest_catalog.json",
            "release/current/stage147_project_manifest_body_pack/manifest_state_bindings.json",
            "release/current/stage147_project_manifest_body_pack/manifest_policy_boundary.json",
            "release/current/stage147_project_manifest_body_pack/manifest_load_order.json",
            "release/current/stage147_project_manifest_body_pack/stage148_entry_signals.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage148": {
        "label": "Stage148",
        "version": "1.48.0",
        "title": "Node Boundary Constitution",
        "required_files": [
            "docs/stages/stage148.md",
            "docs/proposals/stage148_node_boundary_constitution_proposal.md",
            "docs/architecture/stage148_node_boundary_constitution_blueprint.md",
            "docs/development/stage148_developer_handoff.md",
            "manifests/stage148_manifest.json",
            "manifests/stage148_node_boundary_constitution_manifest.json",
            "manifests/stage148_branchpoint_trace_manifest.json",
            "manifests/live_core_stage148_overlay.json",
            "release/current/stage148_release_asset_manifest.json",
            "release/current/stage148_node_boundary_constitution_report.json",
            "release/current/stage148_node_boundary_constitution_pack/node_authority_matrix.json",
            "release/current/stage148_node_boundary_constitution_pack/packet_route_map.json",
            "release/current/stage148_node_boundary_constitution_pack/surface_projection_registry.json",
            "release/current/stage148_node_boundary_constitution_pack/boundary_enforcement_summary.json",
            "release/current/stage148_node_boundary_constitution_pack/stage149_entry_signals.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage149": {
        "label": "Stage149",
        "version": "1.49.0",
        "title": "Body Constitution Release Gate",
        "required_files": [
            "docs/stages/stage149.md",
            "docs/proposals/stage149_body_constitution_release_gate_proposal.md",
            "docs/architecture/stage149_body_constitution_release_gate_blueprint.md",
            "docs/development/stage149_developer_handoff.md",
            "manifests/stage149_manifest.json",
            "manifests/stage149_body_constitution_release_gate_manifest.json",
            "manifests/stage149_branchpoint_trace_manifest.json",
            "manifests/live_core_stage149_overlay.json",
            "release/current/stage149_release_asset_manifest.json",
            "release/current/stage149_body_constitution_release_gate_report.json",
            "release/current/stage149_body_constitution_release_gate_pack/body_constitution_gate_matrix.json",
            "release/current/stage149_body_constitution_release_gate_pack/page01_constitution_seal.json",
            "release/current/stage149_body_constitution_release_gate_pack/stage150_readiness_matrix.json",
            "release/current/stage149_body_constitution_release_gate_pack/release_blocker_registry.json",
            "release/current/stage149_body_constitution_release_gate_pack/lineage_evidence_index.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage150": {
        "label": "Stage150",
        "version": "1.50.0",
        "title": "Memory Contract",
        "required_files": [
            "docs/stages/stage150.md",
            "docs/proposals/stage150_memory_contract_proposal.md",
            "docs/architecture/stage150_memory_contract_blueprint.md",
            "docs/development/stage150_developer_handoff.md",
            "manifests/stage150_manifest.json",
            "manifests/stage150_memory_contract_manifest.json",
            "manifests/stage150_branchpoint_trace_manifest.json",
            "manifests/live_core_stage150_overlay.json",
            "release/current/stage150_release_asset_manifest.json",
            "release/current/stage150_memory_contract_report.json",
            "release/current/stage150_release_gate_report.json",
            "release/current/stage150_memory_contract_pack/preflight15_matrix.json",
            "release/current/stage150_memory_contract_pack/memory_record_contracts.json",
            "release/current/stage150_memory_contract_pack/memory_boundary_policy.json",
            "release/current/stage150_memory_contract_pack/memory_write_policy.json",
            "release/current/stage150_memory_contract_pack/node2_projection_policy.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage151": {
        "label": "Stage151",
        "version": "1.51.0",
        "title": "Local Read-Only Memory Store",
        "required_files": [
            "docs/stages/stage151.md",
            "docs/proposals/stage151_local_read_only_memory_store_proposal.md",
            "docs/architecture/stage151_local_read_only_memory_store_blueprint.md",
            "docs/development/stage151_developer_handoff.md",
            "manifests/stage151_manifest.json",
            "manifests/stage151_local_read_only_memory_store_manifest.json",
            "manifests/stage151_branchpoint_trace_manifest.json",
            "manifests/live_core_stage151_overlay.json",
            "release/current/stage151_release_asset_manifest.json",
            "release/current/stage151_local_read_only_memory_store_report.json",
            "release/current/stage151_release_gate_report.json",
            "release/current/stage151_local_read_only_memory_store_pack/store_spec.json",
            "release/current/stage151_local_read_only_memory_store_pack/record_validation_report.json",
            "release/current/stage151_local_read_only_memory_store_pack/checksum_index.json",
            "release/current/stage151_local_read_only_memory_store_pack/read_only_access_policy.json",
            "release/current/stage151_local_read_only_memory_store_pack/node2_projection_index.json",
            "samples/stage151_memory_store/project_memory_records.jsonl",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage152": {
        "label": "Stage152",
        "version": "1.52.0",
        "title": "Deterministic Local Query / Ranking",
        "required_files": [
            "docs/stages/stage152.md",
            "docs/proposals/stage152_memory_query_interface_proposal.md",
            "docs/architecture/stage152_memory_query_interface_blueprint.md",
            "docs/development/stage152_developer_handoff.md",
            "manifests/stage152_manifest.json",
            "manifests/stage152_memory_query_interface_manifest.json",
            "manifests/stage152_branchpoint_trace_manifest.json",
            "manifests/live_core_stage152_overlay.json",
            "release/current/stage152_release_asset_manifest.json",
            "release/current/stage152_memory_query_interface_report.json",
            "release/current/stage152_release_gate_report.json",
            "release/current/stage152_memory_query_interface_pack/query_api_catalog.json",
            "release/current/stage152_memory_query_interface_pack/query_policy.json",
            "release/current/stage152_memory_query_interface_pack/intent_query_result.json",
            "release/current/stage152_memory_query_interface_pack/type_query_results.json",
            "release/current/stage152_memory_query_interface_pack/ranking_report.json",
            "release/current/stage152_memory_query_interface_pack/node2_projection_report.json",
            ".github/workflows/ci-fast.yml",
        ],
    },    "stage153": {
        "label": "Stage153",
        "version": "1.53.0",
        "title": "Memory Health & Leakage Boundary",
        "required_files": [
            "docs/stages/stage153.md",
            "docs/proposals/stage153_memory_health_leakage_boundary_proposal.md",
            "docs/architecture/stage153_memory_health_leakage_boundary_blueprint.md",
            "docs/development/stage153_developer_handoff.md",
            "manifests/stage153_manifest.json",
            "manifests/stage153_memory_health_leakage_boundary_manifest.json",
            "manifests/stage153_branchpoint_trace_manifest.json",
            "manifests/live_core_stage153_overlay.json",
            "release/current/stage153_release_asset_manifest.json",
            "release/current/stage153_memory_health_leakage_boundary_report.json",
            "release/current/stage153_release_gate_report.json",
            "release/current/stage153_memory_health_leakage_boundary_pack/record_health_report.json",
            "release/current/stage153_memory_health_leakage_boundary_pack/leakage_boundary_scan.json",
            "release/current/stage153_memory_health_leakage_boundary_pack/node2_leakage_matrix.json",
            "release/current/stage153_memory_health_leakage_boundary_pack/query_boundary_probe.json",
            "release/current/stage153_memory_health_leakage_boundary_pack/health_policy.json",
            "release/current/stage153_memory_health_leakage_boundary_pack/regression_snapshot.json",
            ".github/workflows/ci-fast.yml",
        ],
    },

    "stage155": {
        "label": "Stage155",
        "version": "1.55.0",
        "title": "Execution Contract",
        "required_files": [
            "docs/stages/stage155.md",
            "docs/proposals/stage155_execution_contract_proposal.md",
            "docs/architecture/stage155_execution_contract_blueprint.md",
            "docs/development/stage155_developer_handoff.md",
            "docs/proposals/page03_execution_body_proposal.md",
            "docs/architecture/page03_execution_body_blueprint.md",
            "docs/development/page03_developer_handoff.md",
            "docs/roadmaps/seven_page_architecture.md",
            "manifests/stage155_manifest.json",
            "manifests/stage155_execution_contract_manifest.json",
            "manifests/stage155_branchpoint_trace_manifest.json",
            "manifests/live_core_stage155_overlay.json",
            "release/current/stage155_release_asset_manifest.json",
            "release/current/stage155_execution_contract_report.json",
            "release/current/stage155_release_gate_report.json",
            "release/current/stage155_execution_contract_pack/page03_readiness_matrix.json",
            "release/current/stage155_execution_contract_pack/execution_packet_contracts.json",
            "release/current/stage155_execution_contract_pack/execution_boundary_policy.json",
            "release/current/stage155_execution_contract_pack/execution_write_policy.json",
            "release/current/stage155_execution_contract_pack/node2_execution_projection_policy.json",
        ],
    },

    "stage156": {
        "label": "Stage156",
        "version": "1.56.0",
        "title": "Local Execution Packet Store",
        "required_files": [
            "docs/stages/stage156.md",
            "docs/proposals/stage156_local_execution_packet_store_proposal.md",
            "docs/architecture/stage156_local_execution_packet_store_blueprint.md",
            "docs/development/stage156_developer_handoff.md",
            "docs/workflow/PREFLIGHT_GUIDE_gpt_stage156.md",
            "manifests/stage156_manifest.json",
            "manifests/stage156_local_execution_packet_store_manifest.json",
            "manifests/stage156_branchpoint_trace_manifest.json",
            "manifests/live_core_stage156_overlay.json",
            "release/current/stage156_release_asset_manifest.json",
            "release/current/stage156_local_execution_packet_store_report.json",
            "release/current/stage156_release_gate_report.json",
            "release/current/stage156_local_execution_packet_store_pack/packet_store_catalog.json",
            "release/current/stage156_local_execution_packet_store_pack/packet_schema_validation.json",
            "release/current/stage156_local_execution_packet_store_pack/packet_checksum_index.json",
            "release/current/stage156_local_execution_packet_store_pack/read_only_access_policy.json",
            "release/current/stage156_local_execution_packet_store_pack/node2_packet_projection_matrix.json",
            "release/current/stage156_local_execution_packet_store_pack/regression_snapshot.json",
        ],
    },


    "stage157": {
        "label": "Stage157",
        "version": "1.57.0",
        "title": "Deterministic Plan Graph Builder",
        "required_files": [
            "docs/stages/stage157.md",
            "docs/proposals/stage157_deterministic_plan_graph_builder_proposal.md",
            "docs/architecture/stage157_deterministic_plan_graph_builder_blueprint.md",
            "docs/development/stage157_developer_handoff.md",
            "manifests/stage157_manifest.json",
            "manifests/stage157_deterministic_plan_graph_builder_manifest.json",
            "manifests/stage157_branchpoint_trace_manifest.json",
            "manifests/live_core_stage157_overlay.json",
            "release/current/stage157_release_asset_manifest.json",
            "release/current/stage157_deterministic_plan_graph_builder_report.json",
            "release/current/stage157_release_gate_report.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/plan_graph_nodes.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/plan_graph_edges.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/topological_order.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/dependency_integrity.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/deterministic_graph_checksum.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/node2_plan_projection_matrix.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/plan_graph_policy.json",
            "release/current/stage157_deterministic_plan_graph_builder_pack/regression_snapshot.json",
        ],
    },
    "stage154": {
        "label": "Stage154",
        "version": "1.54.0",
        "title": "Page02 Release Seal",
        "required_files": [
            "docs/stages/stage154.md",
            "docs/proposals/stage154_page02_release_seal_proposal.md",
            "docs/architecture/stage154_page02_release_seal_blueprint.md",
            "docs/development/stage154_developer_handoff.md",
            "manifests/stage154_manifest.json",
            "manifests/stage154_page02_release_seal_manifest.json",
            "manifests/stage154_branchpoint_trace_manifest.json",
            "manifests/live_core_stage154_overlay.json",
            "release/current/stage154_release_asset_manifest.json",
            "release/current/stage154_page02_release_seal_report.json",
            "release/current/stage154_release_gate_report.json",
            "release/current/stage154_page02_release_seal_pack/page02_stage_chain.json",
            "release/current/stage154_page02_release_seal_pack/page02_release_seal_matrix.json",
            "release/current/stage154_page02_release_seal_pack/page02_blocker_registry.json",
            "release/current/stage154_page02_release_seal_pack/page02_artifact_index.json",
            "release/current/stage154_page02_release_seal_pack/page02_lineage_evidence_index.json",
            "release/current/stage154_page02_release_seal_pack/page02_boundary_freeze.json",
            ".github/workflows/ci-fast.yml",
        ],
    },
    "stage158": {
        "label": "Stage158",
        "version": "1.58.0",
        "title": "Dependency and Conflict Preflight",
        "required_files": [
            "docs/stages/stage158.md",
            "docs/proposals/stage158_dependency_conflict_preflight_proposal.md",
            "docs/architecture/stage158_dependency_conflict_preflight_blueprint.md",
            "docs/development/stage158_developer_handoff.md",
            "manifests/stage158_manifest.json",
            "manifests/stage158_dependency_conflict_preflight_manifest.json",
            "manifests/stage158_branchpoint_trace_manifest.json",
            "manifests/live_core_stage158_overlay.json",
            "release/current/stage158_release_asset_manifest.json",
            "release/current/stage158_dependency_conflict_preflight_report.json",
            "release/current/stage158_release_gate_report.json",
            "release/current/stage158_dependency_conflict_preflight_pack/dependency_order_preflight.json",
            "release/current/stage158_dependency_conflict_preflight_pack/conflict_matrix.json",
            "release/current/stage158_dependency_conflict_preflight_pack/packet_boundary_preflight.json",
            "release/current/stage158_dependency_conflict_preflight_pack/blocked_operation_registry.json",
            "release/current/stage158_dependency_conflict_preflight_pack/node2_conflict_projection_matrix.json",
            "release/current/stage158_dependency_conflict_preflight_pack/graph_integrity_snapshot.json",
            "release/current/stage158_dependency_conflict_preflight_pack/preflight_step15_connectivity_matrix.json",
            "release/current/stage158_dependency_conflict_preflight_pack/regression_snapshot.json",
        ],
    },
    "stage159": {
        "label": "Stage159",
        "version": "1.59.0",
        "title": "Execution Dry-Run Trace",
        "required_files": [
            "docs/stages/stage159.md",
            "docs/proposals/stage159_execution_dry_run_trace_proposal.md",
            "docs/architecture/stage159_execution_dry_run_trace_blueprint.md",
            "docs/development/stage159_developer_handoff.md",
            "manifests/stage159_manifest.json",
            "manifests/stage159_execution_dry_run_trace_manifest.json",
            "manifests/stage159_branchpoint_trace_manifest.json",
            "manifests/live_core_stage159_overlay.json",
            "release/current/stage159_release_asset_manifest.json",
            "release/current/stage159_execution_dry_run_trace_report.json",
            "release/current/stage159_release_gate_report.json",
            "release/current/stage159_execution_dry_run_trace_pack/dry_run_trace_steps.json",
            "release/current/stage159_execution_dry_run_trace_pack/trace_replay_ledger.json",
            "release/current/stage159_execution_dry_run_trace_pack/side_effect_free_policy.json",
            "release/current/stage159_execution_dry_run_trace_pack/node2_trace_projection_matrix.json",
            "release/current/stage159_execution_dry_run_trace_pack/trace_integrity_snapshot.json",
            "release/current/stage159_execution_dry_run_trace_pack/preflight_step15_connectivity_matrix.json",
            "release/current/stage159_execution_dry_run_trace_pack/stage160_entry_criteria.json",
            "release/current/stage159_execution_dry_run_trace_pack/regression_snapshot.json",
        ],
    },
    "stage160": {
        "label": "Stage160",
        "version": "1.60.0",
        "title": "Page03 Release Seal",
        "required_files": [
            "docs/stages/stage160.md",
            "docs/proposals/stage160_page03_release_seal_proposal.md",
            "docs/architecture/stage160_page03_release_seal_blueprint.md",
            "docs/development/stage160_developer_handoff.md",
            "manifests/stage160_manifest.json",
            "manifests/stage160_page03_release_seal_manifest.json",
            "manifests/stage160_branchpoint_trace_manifest.json",
            "manifests/live_core_stage160_overlay.json",
            "release/current/stage160_release_asset_manifest.json",
            "release/current/stage160_page03_release_seal_report.json",
            "release/current/stage160_release_gate_report.json",
            "release/current/stage160_page03_release_seal_pack/page03_stage_chain.json",
            "release/current/stage160_page03_release_seal_pack/page03_release_seal_matrix.json",
            "release/current/stage160_page03_release_seal_pack/page03_artifact_index.json",
            "release/current/stage160_page03_release_seal_pack/page03_invariant_freeze.json",
            "release/current/stage160_page03_release_seal_pack/page03_nexus_connectivity_matrix.json",
            "release/current/stage160_page03_release_seal_pack/page03_transition_criteria.json",
            "release/current/stage160_page03_release_seal_pack/page03_release_seal.json",
            "release/current/stage160_page03_release_seal_pack/regression_snapshot.json",
        ],
    },
    "stage161": {
        "label": "Stage161",
        "version": "1.61.0",
        "title": "Rendering Contract",
        "required_files": [
            "docs/stages/stage161.md",
            "docs/proposals/stage161_rendering_contract_proposal.md",
            "docs/architecture/stage161_rendering_contract_blueprint.md",
            "docs/development/stage161_developer_handoff.md",
            "docs/proposals/page04_rendering_body_proposal.md",
            "docs/architecture/page04_rendering_body_blueprint.md",
            "docs/development/page04_handoff.md",
            "manifests/stage161_manifest.json",
            "manifests/stage161_rendering_contract_manifest.json",
            "manifests/stage161_branchpoint_trace_manifest.json",
            "manifests/live_core_stage161_overlay.json",
            "release/current/stage161_release_asset_manifest.json",
            "release/current/stage161_rendering_contract_report.json",
            "release/current/stage161_release_gate_report.json",
            "release/current/stage161_rendering_contract_pack/page04_readiness_matrix.json",
            "release/current/stage161_rendering_contract_pack/rendering_contracts.json",
            "release/current/stage161_rendering_contract_pack/rendering_boundary_policy.json",
            "release/current/stage161_rendering_contract_pack/rendering_write_policy.json",
            "release/current/stage161_rendering_contract_pack/node2_rendering_projection_policy.json",
        ],
    },
}


def run_stage_metadata_consistency(root: Path | None = None) -> dict[str, Any]:
    root = root or Path(__file__).resolve().parents[3]
    live = _read_json(root / "manifests/live_core_manifest.json")
    target_stage = str(live.get("active_version", "stage140"))
    target = TARGETS.get(target_stage, TARGETS["stage140"])
    package = _read_json(root / "package_manifest.json")
    pyproject = _read_text(root / "pyproject.toml")
    readme = _read_text(root / "README.md")
    notes = _read_text(root / "RELEASE_NOTES.md")
    active = str(live.get("active_version", ""))
    package_active = str(package.get("active_version", ""))
    package_stage = str(package.get("stage", ""))
    py_version = _py_value(pyproject, "version")
    py_description = _py_value(pyproject, "description")
    label = str(target["label"])
    version = str(target["version"])
    title = str(target["title"])
    required_files = list(target["required_files"])
    checks = [
        _check("live_manifest_active_stage", active == target_stage, target_stage, active, root / "manifests/live_core_manifest.json"),
        _check("readme_current_stage_matches_live", label in readme and title in readme, f"{label} {title}", _excerpt(readme, label), root / "README.md"),
        _check("package_manifest_active_matches_live", package_active == active == target_stage and package_stage == target_stage, target_stage, f"active={package_active}; stage={package_stage}", root / "package_manifest.json"),
        _check("package_manifest_paths_match_stage", all(target_stage in str(package.get(k, "")) for k in ("canonical_package", "patch_report", "release_gate", "asset_manifest")), f"{target_stage} package paths", json.dumps({k: package.get(k, "") for k in ("canonical_package", "patch_report", "release_gate", "asset_manifest")}, sort_keys=True), root / "package_manifest.json"),
        _check("pyproject_version_matches_stage", py_version == version, version, py_version, root / "pyproject.toml"),
        _check("pyproject_description_matches_stage", label in py_description and title in py_description, f"{label} - {title}", py_description, root / "pyproject.toml"),
        _check("release_notes_match_stage", label in notes and title in notes, f"{label} {title}", _excerpt(notes, label), root / "RELEASE_NOTES.md"),
    ]
    for rel in required_files:
        checks.append(_check(f"required_file_present:{rel}", (root / rel).exists(), "file exists", "exists" if (root / rel).exists() else "missing", root / rel))
    issues = tuple(c.name for c in checks if c.status != "pass")
    return IntegrityReport(
        stage=target_stage,
        title="Stage Metadata Consistency",
        status="pass" if not issues else "blocked",
        checks=tuple(checks),
        issues=issues,
        counters={"check_count": len(checks), "pass_count": sum(1 for c in checks if c.status == "pass"), "blocked_count": len(issues)},
    ).to_dict()


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def _py_value(text: str, name: str) -> str:
    match = re.search(rf"(?m)^\s*{re.escape(name)}\s*=\s*\"([^\"]*)\"", text)
    return match.group(1) if match else ""


def _check(name: str, condition: bool, expected: str, actual: str, path: Path) -> IntegrityCheck:
    return IntegrityCheck(name=name, status="pass" if condition else "blocked", expected=expected, actual=actual, path=_display_path(path))


def _display_path(path: Path) -> str:
    try:
        return path.relative_to(Path.cwd()).as_posix()
    except ValueError:
        return path.as_posix()


def _excerpt(text: str, token: str) -> str:
    index = text.find(token)
    return text[:160] if index < 0 else text[max(0, index - 40): index + 120]
