from __future__ import annotations
from .contracts import PluginManifest

def builtin_plugin_manifests() -> list[PluginManifest]:
    return [
        PluginManifest(
            plugin_id="core.genre.literary_thriller",
            name="Literary Thriller Genre Pack",
            version="1.0.0",
            kind="genre_pack",
            entrypoint="v1700.plugins.genre.literary_thriller",
            trust_level="core",
            enabled_by_default=False,
            requires_live_provider=False,
            requires_raw_manuscript=False,
            writes_release_evidence=True,
            branchpoint_trace_id="bp-stage109-genre-pack",
            test_target="tests/test_stage109_plugin_manifest.py",
        ),
        PluginManifest(
            plugin_id="core.evaluator.editorial_scorecard",
            name="Editorial Scorecard Pack",
            version="1.0.0",
            kind="evaluator_pack",
            entrypoint="v1700.plugins.evaluator.editorial_scorecard",
            trust_level="core",
            enabled_by_default=False,
            requires_live_provider=False,
            requires_raw_manuscript=False,
            writes_release_evidence=True,
            branchpoint_trace_id="bp-stage109-evaluator-pack",
            test_target="tests/test_stage109_plugin_manifest.py",
        ),
        PluginManifest(
            plugin_id="core.export.writer_handoff",
            name="Writer Handoff Export Pack",
            version="1.0.0",
            kind="export_pack",
            entrypoint="v1700.plugins.export.writer_handoff",
            trust_level="core",
            enabled_by_default=False,
            requires_live_provider=False,
            requires_raw_manuscript=False,
            writes_release_evidence=True,
            branchpoint_trace_id="bp-stage109-export-pack",
            test_target="tests/test_stage109_plugin_manifest.py",
        ),
        PluginManifest(
            plugin_id="sandbox.provider.live_adapter_probe",
            name="Provider Live Adapter Probe Pack",
            version="0.1.0",
            kind="provider_adapter_pack",
            entrypoint="v1700.plugins.provider.live_adapter_probe",
            trust_level="review_required",
            enabled_by_default=False,
            requires_live_provider=True,
            requires_raw_manuscript=False,
            writes_release_evidence=False,
            branchpoint_trace_id="bp-stage109-provider-adapter-pack",
            test_target="tests/test_stage109_plugin_sandbox_policy.py",
        ),
    ]
