from __future__ import annotations

from v1700.nie.adversarial.contracts import NIEAdversarialCase
from v1700.nie.nil.nil_report import build_stage118_nil_orchestrator_report


def build_stage119_cases() -> tuple[NIEAdversarialCase, ...]:
    normal = build_stage118_nil_orchestrator_report()
    cases: list[NIEAdversarialCase] = [
        NIEAdversarialCase(
            case_id="NIE-NOR-001",
            case_type="normal_nil_loop",
            mutation_type="none",
            expected_status="PASS",
            expected_block_reason=None,
            expected_triggered_gate=None,
            severity="INFO",
            payload={"nil_report": normal},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-001",
            case_type="mae_reward_contract",
            mutation_type="remove_dimension_score",
            expected_status="BLOCK",
            expected_block_reason="mae_dimension_score_missing",
            expected_triggered_gate="mae_reward_contract_gate",
            severity="CRITICAL_BLOCK",
            payload={"dimension_scores": {"tension": 0.7, "sympathy": 0.6, "catharsis": 0.5}},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-002",
            case_type="reward_bridge_boundary",
            mutation_type="bridge_attempts_live_provider_call",
            expected_status="BLOCK",
            expected_block_reason="physics_reward_bridge_llm_call_nonzero",
            expected_triggered_gate="physics_reward_bridge_no_llm_gate",
            severity="CRITICAL_BLOCK",
            payload={"physics_reward_bridge_llm_call_count": 1},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-003",
            case_type="adaptive_momentum_weights",
            mutation_type="alpha_exceeds_bounds",
            expected_status="BLOCK",
            expected_block_reason="amw_alpha_bounds_violation",
            expected_triggered_gate="amw_alpha_bounds_gate",
            severity="BLOCK",
            payload={"alpha_after": {"tension": 0.91, "sympathy": 0.64, "dread": 0.40, "catharsis": 0.55}},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-004",
            case_type="adaptive_momentum_weights",
            mutation_type="run_shift_exceeds_limit",
            expected_status="BLOCK",
            expected_block_reason="amw_run_total_shift_exceeded",
            expected_triggered_gate="amw_drift_guard_gate",
            severity="BLOCK",
            payload={"run_total_shift": 0.143, "limit": 0.10},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-005",
            case_type="character_influence_matrix",
            mutation_type="matrix_symmetric_only",
            expected_status="BLOCK",
            expected_block_reason="cim_asymmetry_missing",
            expected_triggered_gate="cim_asymmetric_matrix_gate",
            severity="CRITICAL_BLOCK",
            payload={"matrix_is_asymmetric": False, "asymmetric_pair_count": 0},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-006",
            case_type="structural_balance",
            mutation_type="triangle_tension_not_computed",
            expected_status="BLOCK",
            expected_block_reason="triangle_tension_missing",
            expected_triggered_gate="structural_balance_gate",
            severity="BLOCK",
            payload={"triangle_count": 0, "high_tension_triangle_count": 0},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-007",
            case_type="role_tier_assignment",
            mutation_type="orphan_character_role_tier",
            expected_status="BLOCK",
            expected_block_reason="role_tier_orphan_character",
            expected_triggered_gate="role_tier_assignment_gate",
            severity="BLOCK",
            payload={"characters": ["minjun", "sujin", "haewon"], "role_tiers": {"minjun": "jang", "sujin": "jang"}},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-008",
            case_type="domain_rag_fusion",
            mutation_type="query_classifier_uses_llm",
            expected_status="BLOCK",
            expected_block_reason="query_classifier_llm_call_nonzero",
            expected_triggered_gate="domain_rag_classifier_no_llm_gate",
            severity="CRITICAL_BLOCK",
            payload={"query_classifier_llm_call_count": 1},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-009",
            case_type="domain_rag_fusion",
            mutation_type="drama_lexicon_boost_missing",
            expected_status="BLOCK",
            expected_block_reason="drama_lexicon_boost_missing",
            expected_triggered_gate="drama_lexicon_boost_gate",
            severity="BLOCK",
            payload={"boosts": {"CHARACTER_NAMES": 1.0, "EPISODE_TERMS": 1.0, "DRAMA_KEYWORDS": 1.0}},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-010",
            case_type="narrative_tension_curve",
            mutation_type="tension_curve_loss_absent",
            expected_status="BLOCK",
            expected_block_reason="narrative_tension_loss_missing",
            expected_triggered_gate="narrative_tension_curve_gate",
            severity="BLOCK",
            payload={"tension_loss": None, "coverage_loss": 0.0, "final_loss": None},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-011",
            case_type="nil_orchestrator_evidence",
            mutation_type="nil_report_lacks_evidence",
            expected_status="BLOCK",
            expected_block_reason="nil_evidence_path_missing",
            expected_triggered_gate="nil_evidence_reproducibility_gate",
            severity="CRITICAL_BLOCK",
            payload={"evidence_path": "", "loop_order": normal.get("loop_order", [])},
        ),
        NIEAdversarialCase(
            case_id="NIE-ADV-012",
            case_type="gate25_detection",
            mutation_type="broken_nie_case_not_detected_by_gate",
            expected_status="BLOCK",
            expected_block_reason="gate_detection_failed",
            expected_triggered_gate="gate25_detection_gate",
            severity="CRITICAL_BLOCK",
            payload={"simulated_gate_detected": False, "unexpected_pass_count": 1},
        ),
    ]
    return tuple(cases)
