from __future__ import annotations

from v1700.lineage_absorption.contracts import (
    AbsorptionCandidate,
    AbsorptionPlan,
    CandidateArchiveAudit,
    ConflictEntry,
    FormulaEntry,
    GateAuthorityEntry,
    LineageRelationship,
)

TRUNK_STAGE = "stage120"
TRUNK_PACKAGE_SHA256 = "27aa90f64abdde79e4363ab2707ffec1a005bbbb15234db3732e3fed740b9955"

CANDIDATE_ARCHIVES: tuple[CandidateArchiveAudit, ...] = (
    CandidateArchiveAudit(
        name="literary_os_v545_HF.zip",
        source_version="V545_HF",
        sha256="eb23125d410ddb905831796990f891a0b108b2cdd23d10d33be55b90f4972978",
        entry_count=14558,
        cache_file_count=715,
        backslash_path_count=0,
        has_internal_filelist=False,
        has_internal_sha256sums=False,
        clean_packaging_pass=False,
        direct_merge_allowed=False,
        observed_modules=["literary_system/nie", "literary_system/graph_intelligence/asd", "gate28"],
        observed_reports=["CHANGELOG_V525_NIE.md", "CHANGELOG_V545_ASD.md", "CHANGELOG_V545_HF.md"],
        notes=["contains pycache/pyc artifacts", "reference only; direct merge blocked"],
    ),
    CandidateArchiveAudit(
        name="literary_os_v546_cleanup.zip",
        source_version="V546_cleanup",
        sha256="e531ac44a8942e9a2c914e9c33b1ba465e4761ac1d49957b208946dec12f42c5",
        entry_count=14629,
        cache_file_count=0,
        backslash_path_count=0,
        has_internal_filelist=False,
        has_internal_sha256sums=False,
        clean_packaging_pass=False,
        direct_merge_allowed=False,
        observed_modules=["literary_system/nie", "literary_system/graph_intelligence/asd", "gate28"],
        observed_reports=["MANIFEST_V525_NIE.md", "CHANGELOG_V545_ASD.md"],
        notes=["cache cleaned but internal FILELIST/SHA256SUMS absent", "reference only"],
    ),
    CandidateArchiveAudit(
        name="literary_os_v555_PNE.zip",
        source_version="V555_PNE",
        sha256="edb3f94b1cae9849a1c1361fa2e41e805076cdb18adae4c8f0f78f1a05bda7d4",
        entry_count=15080,
        cache_file_count=0,
        backslash_path_count=0,
        has_internal_filelist=False,
        has_internal_sha256sums=False,
        clean_packaging_pass=False,
        direct_merge_allowed=False,
        observed_modules=["literary_system/nie", "literary_system/graph_intelligence/asd", "literary_system/predictive", "gate28", "gate29"],
        observed_reports=["MANIFEST_V525_NIE.md", "CHANGELOG_V545_ASD.md", "tests/test_v551_v555_pne.py"],
        notes=["PNE/Gate29 candidate present", "internal FILELIST/SHA256SUMS absent", "direct merge blocked"],
    ),
)

FORMULA_LEDGER: tuple[FormulaEntry, ...] = (
    FormulaEntry(
        formula_id="STAGE120_REWARD_ADVANTAGE_EMA",
        source_lineage="stage120_trunk",
        source_version="Stage120 Gate25 NIE v1.0",
        module_path="src/v1700/nie/reward/physics_reward_bridge.py",
        formula_type="reward_signal",
        expression="R=0.35*reader+0.25*writer+0.25*editor+0.15*cultural; advantage=R-baseline; baseline'=0.95*baseline+0.05*R",
        constants={"reader": 0.35, "writer": 0.25, "editor": 0.25, "cultural": 0.15, "baseline_decay": 0.95, "baseline_lr": 0.05},
        conflicts_with=[],
        absorption_status="KEEP",
        reason="current Gate25 NIE v1.0 reward contract remains primary",
    ),
    FormulaEntry(
        formula_id="STAGE120_AMW_ALPHA_BOUNDS",
        source_lineage="stage120_trunk",
        source_version="Stage114/Stage120",
        module_path="src/v1700/nie/emotion/adaptive_momentum_weights.py",
        formula_type="bounded_calibration",
        expression="delta=alpha*process+(1-alpha)*observation; alpha in [0.30,0.80]; per_update<=0.03; per_run<=0.10",
        constants={"alpha_min": 0.30, "alpha_max": 0.80, "per_update_shift_max": 0.03, "per_run_shift_max": 0.10},
        conflicts_with=["V525_AMW_ALPHA_BOUNDS"],
        absorption_status="KEEP",
        reason="safety-first bounded calibration; V525 wider alpha is deferred until drift adversarial tests exist",
    ),
    FormulaEntry(
        formula_id="V525_AMW_ALPHA_BOUNDS",
        source_lineage="v525_candidate",
        source_version="V525 NIE v2.0 candidate",
        module_path="literary_system/nie/adaptive_momentum_weights.py",
        formula_type="bounded_calibration_candidate",
        expression="alpha in [0.05,0.95]; LR_AMW=0.005",
        constants={"alpha_min": 0.05, "alpha_max": 0.95, "lr_amw": 0.005},
        conflicts_with=["STAGE120_AMW_ALPHA_BOUNDS"],
        absorption_status="DEFER",
        reason="wider alpha range conflicts with Stage120 drift guard; record as experiment-only candidate",
    ),
    FormulaEntry(
        formula_id="STAGE120_TENSION_CURVE",
        source_lineage="stage120_trunk",
        source_version="Stage117/Stage120",
        module_path="src/v1700/nie/arc/narrative_tension_curve.py",
        formula_type="loss_function",
        expression="T_ideal(t)=0.60+0.40*sin(2*pi*t-0.50)+0.20*sin(6*pi*t); L_final=L_tension+0.3*L_coverage",
        constants={"base": 0.60, "primary_amp": 0.40, "primary_phase": -0.50, "secondary_amp": 0.20, "lambda_coverage": 0.30},
        conflicts_with=[],
        absorption_status="KEEP",
        reason="current tension objective remains Gate25 baseline",
    ),
    FormulaEntry(
        formula_id="V545_GATE28_STORY_QUALITY",
        source_lineage="v545_candidate",
        source_version="V545 ASD candidate",
        module_path="literary_system/graph_intelligence/asd/gate28.py",
        formula_type="quality_gate_candidate",
        expression="debt<=0.50; arc<=0.40; high_priority<=5; combined=min(debt*0.55+arc*0.45,1.0)<=0.45",
        constants={"debt_threshold": 0.50, "arc_threshold": 0.40, "high_priority_threshold": 5, "debt_weight": 0.55, "arc_weight": 0.45, "combined_threshold": 0.45},
        conflicts_with=[],
        absorption_status="ADAPT",
        reason="valuable secondary quality gate, but must be introduced after Stage121 reconciliation as Stage123",
    ),
    FormulaEntry(
        formula_id="V545_ASD_PRIORITY_SCORE",
        source_lineage="v545_candidate",
        source_version="V545 ASD candidate",
        module_path="literary_system/graph_intelligence/asd/story_doctor_orchestrator.py",
        formula_type="repair_priority_candidate",
        expression="priority_score=severity*(1+1.5*blast_ratio)",
        constants={"blast_multiplier": 1.5},
        conflicts_with=[],
        absorption_status="ADAPT",
        reason="candidate for ASD repair triage; release mutation must remain dry-run until Stage123",
    ),
    FormulaEntry(
        formula_id="V555_PNE_PREEMPTIVE_GATE",
        source_lineage="v555_candidate",
        source_version="V555 PNE candidate",
        module_path="literary_system/predictive/preemptive_gate.py",
        formula_type="predictive_gate_candidate",
        expression="block if predicted_debt_probability>=0.60",
        constants={"block_threshold": 0.60},
        conflicts_with=[],
        absorption_status="ADAPT",
        reason="use as Gate29 candidate; release gate must use frozen fixtures, not live training",
    ),
    FormulaEntry(
        formula_id="V555_PNE_FEEDBACK_PRECISION_TARGET",
        source_lineage="v555_candidate",
        source_version="V555 PNE candidate",
        module_path="literary_system/predictive/feedback_learner.py",
        formula_type="model_quality_target",
        expression="precision_target>=0.70; positive threshold=0.60",
        constants={"precision_target": 0.70, "positive_threshold": 0.60},
        conflicts_with=[],
        absorption_status="ADAPT",
        reason="0.70 is quality target, not scene approval threshold; must be documented to avoid formula mixing",
    ),
    FormulaEntry(
        formula_id="V555_DEBT_PREDICTOR_RF",
        source_lineage="v555_candidate",
        source_version="V555 PNE candidate",
        module_path="literary_system/predictive/debt_predictor.py",
        formula_type="ml_predictor_candidate",
        expression="RandomForestClassifier(n_estimators=100,max_depth=5,random_state=42,min_samples=5) with heuristic fallback",
        constants={"n_estimators": 100, "max_depth": 5, "random_state": 42, "min_samples": 5},
        conflicts_with=[],
        absorption_status="DEFER",
        reason="predictive ML layer requires frozen model-card fixtures and sklearn-optional fallback before release authority",
    ),
)

CONFLICT_MATRIX: tuple[ConflictEntry, ...] = (
    ConflictEntry("C121-001", "NIE version naming", "Gate25 NIE v1.0", "NIE v2.0", "medium", "Keep Stage120 naming; register V525 as successor candidate", "stage121"),
    ConflictEntry("C121-002", "AMW alpha bounds", "[0.30,0.80]", "[0.05,0.95]", "high", "Keep Stage120 bounds; defer wider range to Stage122 adversarial drift tests", "stage122"),
    ConflictEntry("C121-003", "Gate25 authority", "Stage120 Gate25 primary", "V525 Gate25 candidate", "high", "Do not replace primary Gate25; map V525 Gate25 as Gate25-v2 candidate", "stage122"),
    ConflictEntry("C121-004", "Gate28/Gate29 authority", "not present in Stage120", "candidate secondary gates", "medium", "Introduce as secondary/advisory until Stage125 governor", "stage123-stage125"),
    ConflictEntry("C121-005", "Candidate packaging", "clean ZIP with internal FILELIST/SHA256SUMS", "candidate archives lack internal FILELIST/SHA256SUMS; V545 has cache", "blocker", "Direct merge blocked; extract formulas only", "stage121"),
    ConflictEntry("C121-006", "PNE runtime learning", "release gates deterministic fixtures only", "DebtPredictor can train RandomForest", "high", "Training forbidden in release gate; frozen fixture/model-card required", "stage124"),
)

GATE_AUTHORITY_MAP: tuple[GateAuthorityEntry, ...] = (
    GateAuthorityEntry("Gate25", "stage120_trunk", "NIE v1.0 release authority", "PRIMARY", ["stage112", "stage113", "stage114", "stage115", "stage116", "stage117", "stage118", "stage119"], []),
    GateAuthorityEntry("Gate25-v2", "v525_candidate", "NIE v2.0 stability/metalerner candidate", "ADVISORY", ["Gate25"], ["name collision with Stage120 Gate25", "requires Stage122 adapter"]),
    GateAuthorityEntry("Gate28", "v545_candidate", "ASD story quality / autonomous repair gate", "SECONDARY", ["Gate25"], ["must run dry-run only until Stage123", "must not mutate manuscripts in release gate"]),
    GateAuthorityEntry("Gate29", "v555_candidate", "PNE predictive debt preemptive gate", "ADVISORY", ["Gate25", "Gate28"], ["ML training prohibited in release gate", "requires frozen fixtures and heuristic fallback"]),
    GateAuthorityEntry("Gate25/28/29 Governor", "future_stage125", "single final gate arbitration layer", "BLOCKED", ["Gate25", "Gate28", "Gate29"], ["not implemented in Stage121", "target Stage125"]),
)

ABSORPTION_CANDIDATES: tuple[AbsorptionCandidate, ...] = (
    AbsorptionCandidate("V525-NIL-STABILITY", "V525", "NIE v2.0 stability", 1, "stage122", "ADAPT", ["stage120_nil_adapter", "gate25_v2_namespace_adapter"], ["test_stage122_nil_stability_absorption.py"], ["C121-003"]),
    AbsorptionCandidate("V525-TIDEAL-LEARNER", "V525", "adaptive tension objective", 2, "stage122", "ADAPT", ["stage117_tension_curve_bridge"], ["test_stage122_tideal_learner.py"], []),
    AbsorptionCandidate("V525-TEMPORAL-CIM", "V525", "temporal character influence", 3, "stage122", "ADAPT", ["stage115_cim_bridge"], ["test_stage122_temporal_cim.py"], []),
    AbsorptionCandidate("V545-ASD-GATE28", "V545", "Autonomous Story Doctor", 4, "stage123", "ADAPT", ["dry_run_repair_adapter", "gate28_secondary_adapter"], ["test_stage123_asd_gate28.py"], ["C121-005"]),
    AbsorptionCandidate("V555-PNE-GATE29", "V555", "Predictive Narrative Engine", 5, "stage124", "ADAPT", ["frozen_model_card_adapter", "heuristic_fallback_adapter", "gate29_advisory_adapter"], ["test_stage124_pne_gate29.py"], ["C121-006"]),
    AbsorptionCandidate("GOVERNOR-25-28-29", "future", "Release gate governor", 6, "stage125", "DEFER", ["multi_gate_arbitration_adapter"], ["test_stage125_gate_governor.py"], ["Gate28/Gate29 not absorbed yet"]),
)

ABSORPTION_PLANS: tuple[AbsorptionPlan, ...] = (
    AbsorptionPlan("stage122", "NIE v2.0 Stability Absorption", ["V525-NIL-STABILITY", "V525-TIDEAL-LEARNER", "V525-TEMPORAL-CIM"], ["stage120_nil_adapter", "gate25_v2_namespace_adapter"], ["V525_AMW_ALPHA_BOUNDS wider range"], ["test_stage122_nil_stability_absorption.py"], ["manifests/stage122_manifest.json"], ["release/current/stage122_release_gate_report.json"]),
    AbsorptionPlan("stage123", "ASD / Gate28 Absorption", ["V545-ASD-GATE28"], ["dry_run_repair_adapter", "gate28_secondary_adapter"], ["candidate direct merge due packaging"], ["test_stage123_asd_gate28.py"], ["manifests/stage123_manifest.json"], ["release/current/stage123_release_gate_report.json"]),
    AbsorptionPlan("stage124", "PNE / Gate29 Absorption", ["V555-PNE-GATE29"], ["frozen_model_card_adapter", "heuristic_fallback_adapter"], ["release-gate runtime training"], ["test_stage124_pne_gate29.py"], ["manifests/stage124_manifest.json"], ["release/current/stage124_release_gate_report.json"]),
    AbsorptionPlan("stage125", "Gate25/28/29 Governor", ["GOVERNOR-25-28-29"], ["multi_gate_arbitration_adapter"], ["unabsorbed Gate28/Gate29"], ["test_stage125_gate_governor.py"], ["manifests/stage125_manifest.json"], ["release/current/stage125_release_gate_report.json"]),
    AbsorptionPlan("stage126", "Cross-Lineage Intelligence Release", ["V525", "V545", "V555"], ["clean_packaging_adapter", "cross_lineage_release_manifest"], ["any unresolved C121 conflict"], ["test_stage126_cross_lineage_release.py"], ["manifests/stage126_manifest.json"], ["release/current/stage126_release_gate_report.json"]),
)
