from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

KNOWN_ACTIVE_VERSIONS = {
    "stage72", "stage72.1", "stage72.2", "stage72.3", "stage73", "stage73.1",
    "stage74", "stage75", "stage76", "stage77", "stage78", "stage79", "stage80",
    "stage81", "stage81.1", "stage82", "stage83", "stage83.1", "stage84", "stage85",
    "stage86", "stage87", "stage88", "stage89", "stage90", "stage91", "stage92",
    "stage93", "stage94", "stage95", "stage96", "stage97", "stage97.1", "stage97.2",
    "stage98", "stage99", "stage100", "stage101", "stage102", "stage103", "stage104",
    "stage105", "stage106", "stage107", "stage107_5", "stage108", "stage109", "stage110",
    "stage111", "stage112", "stage113", "stage114", "stage115", "stage116", "stage117",
    "stage118", "stage119", "stage120", "stage121", "stage122", "stage123", "stage124",
    "stage125", "stage126", "stage127", "stage128", "stage129", "stage130", "stage131",
    "stage132", "stage133", "stage134", "stage135", "stage136", "stage137", "stage138", "stage139", "stage140", "stage141", "stage142", "stage143", "stage144", "stage145", "stage146", "stage147", "stage148", "stage149", "stage150", "stage151", "stage151",
}

STAGE_REQUIRED_GATES = {
    "stage112": ["stage112_gitnexus_nie_preflight", "stage112_release_gate"],
    "stage113": ["stage113_physics_reward_bridge", "stage113_release_gate"],
    "stage114": ["stage114_adaptive_momentum_weights", "stage114_release_gate"],
    "stage115": ["stage115_character_influence_matrix", "stage115_release_gate"],
    "stage116": ["stage116_domain_rag_fusion", "stage116_release_gate"],
    "stage117": ["stage117_narrative_tension_curve", "stage117_release_gate"],
    "stage118": ["stage118_nil_orchestrator", "stage118_release_gate"],
    "stage119": ["stage119_nie_adversarial_regression", "stage119_release_gate"],
    "stage120": ["stage120_gate25_nie_v1", "stage120_release_gate"],
    "stage121": ["stage121_cross_lineage_preflight", "stage121_release_gate"],
    "stage122": ["stage122_nie_v2_stability_absorption", "stage122_release_gate"],
    "stage123": ["stage123_asd_gate28_absorption", "stage123_release_gate"],
    "stage124": ["stage124_pne_gate29_absorption", "stage124_release_gate"],
    "stage125": ["stage125_gate25_28_29_governor", "stage125_release_gate"],
    "stage126": ["stage126_cross_lineage_release", "stage126_release_gate"],
    "stage127": ["stage127_multiwork_preflight", "stage127_release_gate"],
    "stage128": ["stage128_read_only_absorption", "stage128_release_gate"],
    "stage129": ["stage129_multiwork_cim_governor", "stage129_release_gate"],
    "stage130": ["stage130_multiwork_release", "stage130_release_gate"],
    "stage131": ["stage131_gig_advisory", "stage131_release_gate"],
    "stage132": ["stage132_contradiction_classifier", "stage132_release_gate"],
    "stage133": ["stage133_narrative_state_tensor", "stage133_release_gate"],
    "stage134": ["stage134_meta_learner_audit", "stage134_release_gate"],
    "stage135": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
    ],
    "stage136": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
    ],
    "stage137": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
    ],
    "stage138": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
    ],
    "stage139": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
    ],
    "stage140": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
    ],
    "stage141": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
    ],
    "stage142": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
    ],
    "stage143": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
    ],
    "stage144": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
    ],
    "stage145": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
        "stage145_body_constitution",
        "stage145_release_gate",
    ],
    "stage146": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
        "stage145_body_constitution",
        "stage145_release_gate",
        "stage146_narrative_state_contract",
        "stage146_release_gate",
    ],
    "stage147": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
        "stage145_body_constitution",
        "stage145_release_gate",
        "stage146_narrative_state_contract",
        "stage146_release_gate",
        "stage147_project_manifest_body",
        "stage147_release_gate",
    ],
    "stage148": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
        "stage145_body_constitution",
        "stage145_release_gate",
        "stage146_narrative_state_contract",
        "stage146_release_gate",
        "stage147_project_manifest_body",
        "stage147_release_gate",
        "stage148_node_boundary_constitution",
        "stage148_release_gate",
    ],
    "stage149": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
        "stage145_body_constitution",
        "stage145_release_gate",
        "stage146_narrative_state_contract",
        "stage146_release_gate",
        "stage147_project_manifest_body",
        "stage147_release_gate",
        "stage148_node_boundary_constitution",
        "stage148_release_gate",
        "stage149_body_constitution_release_gate",
        "stage149_release_gate",
    ],
    "stage150": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
        "stage145_body_constitution",
        "stage145_release_gate",
        "stage146_narrative_state_contract",
        "stage146_release_gate",
        "stage147_project_manifest_body",
        "stage147_release_gate",
        "stage148_node_boundary_constitution",
        "stage148_release_gate",
        "stage149_body_constitution_release_gate",
        "stage149_release_gate",
        "stage150_memory_contract",
        "stage150_release_gate",
    ],
    "stage151": [
        "stage134_meta_learner_audit",
        "stage134_release_gate",
        "stage135_learning_quality_gate",
        "stage135_release_gate",
        "stage136_schema_registry",
        "stage136_release_gate",
        "stage137_migration_manager",
        "stage137_release_gate",
        "stage138_losdb_storage_contracts",
        "stage138_release_gate",
        "stage139_corpus_governance_pipeline",
        "stage139_release_gate",
        "stage140_release_integrity",
        "stage140_release_gate",
        "stage141_prose_generation_e2e",
        "stage141_release_gate",
        "stage142_longform_benchmark_pack",
        "stage142_release_gate",
        "stage143_user_cli_api_docs",
        "stage143_release_gate",
        "stage144_split_ci_runtime_strategy",
        "stage144_release_gate",
        "stage145_body_constitution",
        "stage145_release_gate",
        "stage146_narrative_state_contract",
        "stage146_release_gate",
        "stage147_project_manifest_body",
        "stage147_release_gate",
        "stage148_node_boundary_constitution",
        "stage148_release_gate",
        "stage149_body_constitution_release_gate",
        "stage149_release_gate",
        "stage150_memory_contract",
        "stage150_release_gate",
        "stage151_local_read_only_memory_store",
        "stage151_release_gate",
    ],
}

STAGE_REQUIRED_FILES = {
    "stage127": [
        "manifests/stage127_manifest.json",
        "manifests/stage127_multiwork_preflight_manifest.json",
        "manifests/stage127_branchpoint_trace_manifest.json",
        "docs/stages/stage127.md",
        "release/current/stage127_multiwork_preflight_report.json",
        "release/current/stage127_release_gate_report.json",
    ],
    "stage128": [
        "manifests/stage128_manifest.json",
        "manifests/stage128_read_only_absorption_manifest.json",
        "manifests/stage128_branchpoint_trace_manifest.json",
        "docs/stages/stage128.md",
        "release/current/stage128_read_only_absorption_report.json",
        "release/current/stage128_release_gate_report.json",
    ],
    "stage129": [
        "manifests/stage129_manifest.json",
        "manifests/stage129_multiwork_cim_governor_manifest.json",
        "manifests/stage129_branchpoint_trace_manifest.json",
        "docs/stages/stage129.md",
        "docs/architecture/stage129_blueprint.md",
        "docs/proposals/stage129_proposal.md",
        "release/current/stage129_multiwork_cim_governor_report.json",
        "release/current/stage129_release_gate_report.json",
    ],
    "stage130": [
        "manifests/stage130_manifest.json",
        "manifests/stage130_multiwork_release_manifest.json",
        "manifests/stage130_branchpoint_trace_manifest.json",
        "docs/stages/stage130.md",
        "docs/architecture/stage130_blueprint.md",
        "docs/proposals/stage130_proposal.md",
        "release/current/stage130_multiwork_release_report.json",
        "release/current/stage130_release_gate_report.json",
    ],
    "stage131": [
        "manifests/stage131_manifest.json",
        "manifests/stage131_gig_advisory_manifest.json",
        "manifests/stage131_branchpoint_trace_manifest.json",
        "docs/stages/stage131.md",
        "docs/architecture/stage131_blueprint.md",
        "docs/proposals/stage131_proposal.md",
        "docs/roadmaps/stage131_roadmap.md",
        "release/current/stage131_gig_advisory_report.json",
        "release/current/stage131_release_gate_report.json",
    ],
    "stage132": [
        "manifests/stage132_manifest.json",
        "manifests/stage132_contradiction_classifier_manifest.json",
        "manifests/stage132_branchpoint_trace_manifest.json",
        "docs/stages/stage132.md",
        "docs/architecture/stage132_blueprint.md",
        "docs/proposals/stage132_proposal.md",
        "docs/roadmaps/stage132_roadmap.md",
        "release/current/stage132_contradiction_classifier_report.json",
        "release/current/stage132_release_gate_report.json",
    ],
    "stage133": [
        "manifests/stage133_manifest.json",
        "manifests/stage133_narrative_state_tensor_manifest.json",
        "manifests/stage133_branchpoint_trace_manifest.json",
        "docs/stages/stage133.md",
        "docs/architecture/stage133_blueprint.md",
        "docs/proposals/stage133_proposal.md",
        "docs/roadmaps/stage133_roadmap.md",
        "release/current/stage133_narrative_state_tensor_report.json",
        "release/current/stage133_release_gate_report.json",
    ],
    "stage134": [
        "manifests/stage134_manifest.json",
        "manifests/stage134_meta_learner_audit_manifest.json",
        "manifests/stage134_branchpoint_trace_manifest.json",
        "docs/stages/stage134.md",
        "docs/architecture/stage134_blueprint.md",
        "docs/proposals/stage134_proposal.md",
        "docs/roadmaps/stage134_roadmap.md",
        "release/current/stage134_meta_learner_audit_report.json",
        "release/current/stage134_release_gate_report.json",
    ],
    "stage135": [
        "manifests/stage135_manifest.json",
        "manifests/stage135_learning_quality_gate_manifest.json",
        "docs/stages/stage135.md",
        "docs/architecture/stage135_blueprint.md",
        "docs/proposals/stage135_proposal.md",
        "release/current/stage135_learning_quality_gate_report.json",
        "release/current/stage135_release_gate_report.json",
        "release/current/stage135_official_asset_manifest.json",
        "release/current/stage135_learning_quality_gate_pack/candidate_registry.json",
        "release/current/stage135_learning_quality_gate_pack/stage135_preflight_report.json",
    ],
    "stage136": [
        "manifests/stage136_manifest.json",
        "manifests/stage136_schema_registry_manifest.json",
        "manifests/stage136_branchpoint_trace_manifest.json",
        "manifests/live_core_stage136_overlay.json",
        "docs/stages/stage136.md",
        "docs/architecture/stage136_blueprint.md",
        "docs/proposals/stage136_proposal.md",
        "docs/development/stage136_developer_handoff.md",
        "release/current/stage136_schema_registry_report.json",
        "release/current/stage136_release_gate_report.json",
        "release/current/stage136_release_asset_manifest.json",
        "release/current/stage136_schema_registry_pack/schema_registry.json",
        "release/current/stage136_schema_registry_pack/stage136_preflight_report.json",
    ],
    "stage137": [
        "manifests/stage137_manifest.json",
        "manifests/stage137_migration_manager_manifest.json",
        "manifests/stage137_branchpoint_trace_manifest.json",
        "manifests/live_core_stage137_overlay.json",
        "docs/stages/stage137.md",
        "docs/architecture/stage137_blueprint.md",
        "docs/proposals/stage137_proposal.md",
        "docs/development/stage137_developer_handoff.md",
        "release/current/stage137_migration_manager_report.json",
        "release/current/stage137_release_gate_report.json",
        "release/current/stage137_release_asset_manifest.json",
        "release/current/stage137_migration_manager_pack/migration_plan.json",
        "release/current/stage137_migration_manager_pack/stage137_preflight_report.json",
    ],
    "stage138": [
        "manifests/stage138_manifest.json",
        "manifests/stage138_losdb_storage_contracts_manifest.json",
        "manifests/stage138_branchpoint_trace_manifest.json",
        "manifests/live_core_stage138_overlay.json",
        "docs/stages/stage138.md",
        "docs/architecture/stage138_blueprint.md",
        "docs/proposals/stage138_proposal.md",
        "docs/development/stage138_developer_handoff.md",
        "release/current/stage138_losdb_storage_contracts_report.json",
        "release/current/stage138_release_gate_report.json",
        "release/current/stage138_release_asset_manifest.json",
        "release/current/stage138_losdb_storage_contracts_pack/storage_contract_catalog.json",
        "release/current/stage138_losdb_storage_contracts_pack/stage138_preflight_report.json",
    ],
    "stage139": [
        "manifests/stage139_manifest.json",
        "manifests/stage139_corpus_governance_pipeline_manifest.json",
        "manifests/stage139_branchpoint_trace_manifest.json",
        "manifests/live_core_stage139_overlay.json",
        "docs/stages/stage139.md",
        "docs/architecture/stage139_blueprint.md",
        "docs/proposals/stage139_proposal.md",
        "docs/development/stage139_developer_handoff.md",
        "release/current/stage139_corpus_governance_pipeline_report.json",
        "release/current/stage139_release_gate_report.json",
        "release/current/stage139_release_asset_manifest.json",
        "release/current/stage139_corpus_governance_pipeline_pack/governance_pipeline.json",
        "release/current/stage139_corpus_governance_pipeline_pack/stage139_preflight_report.json",
    ],
    "stage140": [
        "manifests/stage140_manifest.json",
        "manifests/stage140_release_integrity_manifest.json",
        "manifests/stage140_branchpoint_trace_manifest.json",
        "manifests/live_core_stage140_overlay.json",
        "docs/stages/stage140.md",
        "docs/architecture/stage140_release_integrity_product_proof_blueprint.md",
        "docs/proposals/stage140_release_integrity_product_proof_proposal.md",
        "docs/development/stage140_developer_handoff.md",
        "release/current/stage140_release_integrity_report.json",
        "release/current/stage140_release_gate_report.json",
        "release/current/stage140_release_asset_manifest.json",
        "release/current/stage140_release_integrity_pack/metadata_consistency_report.json",
        "release/current/stage140_release_integrity_pack/release_asset_integrity_report.json",
        "release/current/stage140_release_integrity_pack/sample_project_contract_report.json",
        "release/current/stage140_release_integrity_pack/benchmark_contract_report.json",
    ],
    "stage141": [
        "manifests/stage141_manifest.json",
        "manifests/stage141_prose_generation_e2e_manifest.json",
        "manifests/stage141_branchpoint_trace_manifest.json",
        "manifests/live_core_stage141_overlay.json",
        "docs/stages/stage141.md",
        "docs/architecture/stage141_blueprint.md",
        "docs/proposals/stage141_proposal.md",
        "docs/development/stage141_developer_handoff.md",
        "release/current/stage141_prose_generation_e2e_report.json",
        "release/current/stage141_release_gate_report.json",
        "release/current/stage141_release_asset_manifest.json",
        "release/current/stage141_prose_generation_e2e_pack/rendered_scene.json",
        "release/current/stage141_prose_generation_e2e_pack/benchmark_result.json",
        "benchmarks/longform_output/results/stage141_scene_001_benchmark_result.json",
    ],
    "stage142": [
        "manifests/stage142_manifest.json",
        "manifests/stage142_longform_benchmark_pack_manifest.json",
        "manifests/stage142_branchpoint_trace_manifest.json",
        "manifests/live_core_stage142_overlay.json",
        "docs/stages/stage142.md",
        "docs/architecture/stage142_blueprint.md",
        "docs/proposals/stage142_proposal.md",
        "docs/development/stage142_developer_handoff.md",
        "release/current/stage142_longform_benchmark_pack_report.json",
        "release/current/stage142_release_gate_report.json",
        "release/current/stage142_release_asset_manifest.json",
        "release/current/stage142_longform_benchmark_pack/benchmark_scoreboard.json",
        "release/current/stage142_longform_benchmark_pack/rendered_samples.json",
        "benchmarks/longform_output/results/stage142_benchmark_pack_summary.json",
        "benchmarks/longform_output/results/stage142_rendered_samples.json",
    ],
    "stage143": [
        "manifests/stage143_manifest.json",
        "manifests/stage143_user_cli_api_docs_manifest.json",
        "manifests/stage143_branchpoint_trace_manifest.json",
        "manifests/live_core_stage143_overlay.json",
        "docs/stages/stage143.md",
        "docs/architecture/stage143_blueprint.md",
        "docs/proposals/stage143_proposal.md",
        "docs/development/stage143_developer_handoff.md",
        "docs/user/cli_quickstart.md",
        "docs/user/api_minimum.md",
        "docs/user/examples/render_request.json",
        "docs/user/examples/render_response.json",
        "release/current/stage143_user_cli_api_docs_report.json",
        "release/current/stage143_release_gate_report.json",
        "release/current/stage143_release_asset_manifest.json",
        "release/current/stage143_user_cli_api_docs_pack/cli_contract.json",
        "release/current/stage143_user_cli_api_docs_pack/api_contract.json",
        "release/current/stage143_user_cli_api_docs_pack/user_docs_index.json",
    ],
    "stage144": [
        "manifests/stage144_manifest.json",
        "manifests/stage144_split_ci_runtime_strategy_manifest.json",
        "manifests/stage144_branchpoint_trace_manifest.json",
        "manifests/live_core_stage144_overlay.json",
        "docs/stages/stage144.md",
        "docs/architecture/stage144_blueprint.md",
        "docs/proposals/stage144_proposal.md",
        "docs/development/stage144_developer_handoff.md",
        ".github/workflows/ci-fast.yml",
        "release/current/stage144_split_ci_runtime_strategy_report.json",
        "release/current/stage144_release_gate_report.json",
        "release/current/stage144_release_asset_manifest.json",
        "release/current/stage144_split_ci_runtime_strategy_pack/workflow_inventory.json",
        "release/current/stage144_split_ci_runtime_strategy_pack/runtime_lane_matrix.json",
        "release/current/stage144_split_ci_runtime_strategy_pack/workflow_trigger_summary.json",
        "release/current/stage144_split_ci_runtime_strategy_pack/release_surface_contract.json",
    ],
    "stage145": [
        "manifests/stage145_manifest.json",
        "manifests/stage145_body_constitution_manifest.json",
        "manifests/stage145_branchpoint_trace_manifest.json",
        "manifests/live_core_stage145_overlay.json",
        "docs/stages/stage145.md",
        "docs/architecture/stage145_body_constitution_blueprint.md",
        "docs/proposals/stage145_body_constitution_proposal.md",
        "docs/development/stage145_developer_handoff.md",
        "release/current/stage145_body_constitution_report.json",
        "release/current/stage145_release_gate_report.json",
        "release/current/stage145_release_asset_manifest.json",
        "release/current/stage145_body_constitution_pack/formula_classification.json",
        "release/current/stage145_body_constitution_pack/constitution_invariants.json",
        "release/current/stage145_body_constitution_pack/body_layer_map.json",
        "release/current/stage145_body_constitution_pack/stage150_entry_criteria.json",
    ],
    "stage146": [
        "manifests/stage146_manifest.json",
        "manifests/stage146_narrative_state_contract_manifest.json",
        "manifests/stage146_branchpoint_trace_manifest.json",
        "manifests/live_core_stage146_overlay.json",
        "docs/stages/stage146.md",
        "docs/architecture/stage146_narrative_state_contract_blueprint.md",
        "docs/proposals/stage146_narrative_state_contract_proposal.md",
        "docs/development/stage146_developer_handoff.md",
        "release/current/stage146_narrative_state_contract_report.json",
        "release/current/stage146_release_gate_report.json",
        "release/current/stage146_release_asset_manifest.json",
        "release/current/stage146_narrative_state_contract_pack/state_shape_catalog.json",
        "release/current/stage146_narrative_state_contract_pack/state_hierarchy.json",
        "release/current/stage146_narrative_state_contract_pack/continuity_rulebook.json",
        "release/current/stage146_narrative_state_contract_pack/reveal_boundary_matrix.json",
        "release/current/stage146_narrative_state_contract_pack/stage147_entry_signals.json",
    ],
    "stage147": [
        "manifests/stage147_manifest.json",
        "manifests/stage147_project_manifest_body_manifest.json",
        "manifests/stage147_branchpoint_trace_manifest.json",
        "manifests/live_core_stage147_overlay.json",
        "docs/stages/stage147.md",
        "docs/architecture/stage147_project_manifest_body_blueprint.md",
        "docs/proposals/stage147_project_manifest_body_proposal.md",
        "docs/development/stage147_developer_handoff.md",
        "release/current/stage147_project_manifest_body_report.json",
        "release/current/stage147_release_gate_report.json",
        "release/current/stage147_release_asset_manifest.json",
        "release/current/stage147_project_manifest_body_pack/canonical_manifest_bundle.json",
        "release/current/stage147_project_manifest_body_pack/project_manifest_catalog.json",
        "release/current/stage147_project_manifest_body_pack/manifest_state_bindings.json",
        "release/current/stage147_project_manifest_body_pack/manifest_policy_boundary.json",
        "release/current/stage147_project_manifest_body_pack/manifest_load_order.json",
        "release/current/stage147_project_manifest_body_pack/stage148_entry_signals.json",
    ],
    "stage148": [
        "manifests/stage148_manifest.json",
        "manifests/stage148_node_boundary_constitution_manifest.json",
        "manifests/stage148_branchpoint_trace_manifest.json",
        "manifests/live_core_stage148_overlay.json",
        "docs/stages/stage148.md",
        "docs/architecture/stage148_node_boundary_constitution_blueprint.md",
        "docs/proposals/stage148_node_boundary_constitution_proposal.md",
        "docs/development/stage148_developer_handoff.md",
        "release/current/stage148_node_boundary_constitution_report.json",
        "release/current/stage148_release_gate_report.json",
        "release/current/stage148_release_asset_manifest.json",
        "release/current/stage148_node_boundary_constitution_pack/node_authority_matrix.json",
        "release/current/stage148_node_boundary_constitution_pack/packet_route_map.json",
        "release/current/stage148_node_boundary_constitution_pack/surface_projection_registry.json",
        "release/current/stage148_node_boundary_constitution_pack/boundary_enforcement_summary.json",
        "release/current/stage148_node_boundary_constitution_pack/stage149_entry_signals.json",
    ],
    "stage149": [
        "manifests/stage149_manifest.json",
        "manifests/stage149_body_constitution_release_gate_manifest.json",
        "manifests/stage149_branchpoint_trace_manifest.json",
        "manifests/live_core_stage149_overlay.json",
        "docs/stages/stage149.md",
        "docs/architecture/stage149_body_constitution_release_gate_blueprint.md",
        "docs/proposals/stage149_body_constitution_release_gate_proposal.md",
        "docs/development/stage149_developer_handoff.md",
        "release/current/stage149_body_constitution_release_gate_report.json",
        "release/current/stage149_release_gate_report.json",
        "release/current/stage149_release_asset_manifest.json",
        "release/current/stage149_body_constitution_release_gate_pack/body_constitution_gate_matrix.json",
        "release/current/stage149_body_constitution_release_gate_pack/page01_constitution_seal.json",
        "release/current/stage149_body_constitution_release_gate_pack/stage150_readiness_matrix.json",
        "release/current/stage149_body_constitution_release_gate_pack/release_blocker_registry.json",
        "release/current/stage149_body_constitution_release_gate_pack/lineage_evidence_index.json",
    ],
    "stage150": [
        "manifests/stage150_manifest.json",
        "manifests/stage150_memory_contract_manifest.json",
        "manifests/stage150_branchpoint_trace_manifest.json",
        "manifests/live_core_stage150_overlay.json",
        "docs/stages/stage150.md",
        "docs/architecture/stage150_memory_contract_blueprint.md",
        "docs/proposals/stage150_memory_contract_proposal.md",
        "docs/development/stage150_developer_handoff.md",
        "release/current/stage150_memory_contract_report.json",
        "release/current/stage150_release_gate_report.json",
        "release/current/stage150_release_asset_manifest.json",
        "release/current/stage150_memory_contract_pack/preflight15_matrix.json",
        "release/current/stage150_memory_contract_pack/memory_record_contracts.json",
        "release/current/stage150_memory_contract_pack/memory_boundary_policy.json",
        "release/current/stage150_memory_contract_pack/memory_write_policy.json",
        "release/current/stage150_memory_contract_pack/node2_projection_policy.json",
    ],
    "stage151": [
        "manifests/stage151_manifest.json",
        "manifests/stage151_local_read_only_memory_store_manifest.json",
        "manifests/stage151_branchpoint_trace_manifest.json",
        "manifests/live_core_stage151_overlay.json",
        "docs/stages/stage151.md",
        "docs/architecture/stage151_local_read_only_memory_store_blueprint.md",
        "docs/proposals/stage151_local_read_only_memory_store_proposal.md",
        "docs/development/stage151_developer_handoff.md",
        "release/current/stage151_local_read_only_memory_store_report.json",
        "release/current/stage151_release_gate_report.json",
        "release/current/stage151_release_asset_manifest.json",
        "release/current/stage151_local_read_only_memory_store_pack/store_spec.json",
        "release/current/stage151_local_read_only_memory_store_pack/record_validation_report.json",
        "release/current/stage151_local_read_only_memory_store_pack/checksum_index.json",
        "release/current/stage151_local_read_only_memory_store_pack/read_only_access_policy.json",
        "release/current/stage151_local_read_only_memory_store_pack/node2_projection_index.json",
        "samples/stage151_memory_store/project_memory_records.jsonl",
    ],
}

PREDECESSOR_GATE = {
    "stage113": "stage112_release_gate",
    "stage114": "stage113_release_gate",
    "stage115": "stage114_release_gate",
    "stage116": "stage115_release_gate",
    "stage117": "stage116_release_gate",
    "stage118": "stage117_release_gate",
    "stage119": "stage118_release_gate",
    "stage120": "stage119_release_gate",
    "stage121": "stage120_release_gate",
    "stage122": "stage121_release_gate",
    "stage123": "stage122_release_gate",
    "stage124": "stage123_release_gate",
    "stage125": "stage124_release_gate",
    "stage126": "stage125_release_gate",
    "stage127": "stage126_release_gate",
    "stage128": "stage127_release_gate",
    "stage129": "stage128_release_gate",
    "stage130": "stage129_release_gate",
    "stage131": "stage130_release_gate",
    "stage132": "stage131_release_gate",
    "stage133": "stage132_release_gate",
    "stage134": "stage133_release_gate",
    "stage135": "stage134_release_gate",
    "stage136": "stage135_release_gate",
    "stage137": "stage136_release_gate",
    "stage138": "stage137_release_gate",
    "stage139": "stage138_release_gate",
    "stage140": "stage139_release_gate",
    "stage141": "stage140_release_gate",
    "stage142": "stage141_release_gate",
    "stage143": "stage142_release_gate",
    "stage144": "stage143_release_gate",
    "stage145": "stage144_release_gate",
    "stage146": "stage145_release_gate",
    "stage147": "stage146_release_gate",
    "stage148": "stage147_release_gate",
    "stage149": "stage148_release_gate",
    "stage150": "stage149_release_gate",
    "stage151": "stage150_release_gate",
}


def main() -> int:
    issues: list[str] = []
    required = [
        "src/v1700/cli.py",
        "src/v1700/nodes/node2_prose_renderer/compiler.py",
        "manifests/live_core_manifest.json",
        "manifests/stage_lineage_manifest.json",
        "docs/stages/STAGE_INDEX.md",
    ]
    for rel in required:
        if not (ROOT / rel).exists():
            issues.append(f"missing:{rel}")
    root_py = [p.name for p in ROOT.glob("*.py")]
    if root_py:
        issues.append(f"root_python_files_present:{root_py}")

    manifest = json.loads((ROOT / "manifests/live_core_manifest.json").read_text(encoding="utf-8"))
    active = manifest.get("active_version")
    gates = set(manifest.get("active_gates", []))
    if active not in KNOWN_ACTIVE_VERSIONS:
        issues.append("live_core_manifest_active_version_unknown")

    for gate in STAGE_REQUIRED_GATES.get(active, []):
        if gate not in gates:
            issues.append(f"{gate}_missing")

    predecessor_gate = PREDECESSOR_GATE.get(active)
    if predecessor_gate and predecessor_gate not in gates:
        issues.append(f"{predecessor_gate}_missing")

    for rel in STAGE_REQUIRED_FILES.get(active, []):
        if not (ROOT / rel).exists():
            issues.append(f"missing:{rel}")

    result = {"status": "pass" if not issues else "blocked", "active_version": active, "root_python_files": root_py, "issues": issues}
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if not issues else 1


if __name__ == "__main__":
    raise SystemExit(main())
